// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFeKebGHhno7px4lTS_VmwAbomJCtD2is',
    appId: '1:950440205801:web:d0c57035fbc1b64e74ff78',
    messagingSenderId: '950440205801',
    projectId: 'apprenticeapp-1aea3',
    authDomain: 'apprenticeapp-1aea3.firebaseapp.com',
    storageBucket: 'apprenticeapp-1aea3.firebasestorage.app',
    measurementId: 'G-ZZK620QRH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSb3fmeHtZQ-vJw3n7EotgmUK534HRwfE',
    appId: '1:950440205801:android:17a274c387e90a2d74ff78',
    messagingSenderId: '950440205801',
    projectId: 'apprenticeapp-1aea3',
    storageBucket: 'apprenticeapp-1aea3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFeKebGHhno7px4lTS_VmwAbomJCtD2is',
    appId: '1:950440205801:web:75df17425699d93974ff78',
    messagingSenderId: '950440205801',
    projectId: 'apprenticeapp-1aea3',
    authDomain: 'apprenticeapp-1aea3.firebaseapp.com',
    storageBucket: 'apprenticeapp-1aea3.firebasestorage.app',
    measurementId: 'G-W2WH2WRJ4D',
  );
}
